export const tooltips = {
  campaign: {
    name: "The name of the campaign",
    status: "The status of the campaign",
    objective: "The objective of the campaign, e.g. 'Awareness'",
  },
  adset: {
    name: "The name of the adset",
    campaign: "The campaign the adset belongs to",
    daily_budget: "The daily budget of the adset",
    start_time: "The start time of the adset",
    end_time: "The end time of the adset",
    min_age: "The minimum age of the audience",
    max_age: "The maximum age of the audience",
    optimization_goal: "The optimization goal of the adset, e.g. 'Link Clicks'",
    billing_event: "The billing event of the adset, e.g. 'Impressions'",
    conversion_location: "The conversion location of the adset, e.g. 'Website'",
    gender: "The gender of the audience",
    location: "The location of the audience",
    interests: "The interests of the audience",
    page_id: "The social media page ID for the adset",
    application_id: "The application ID of the targeted app",
    object_store_url: "The object store URL of the app",
  },
  ad: {
    campaign: "The campaign the ad belongs to",
    adset: "The adset the ad belongs to",
    variant: "The variant the ad belongs to",
    name: "The name of the ad",
    status: "The status of the ad",
    headline: "The headline of the ad",
    primary_text: "The primary text of the ad",
    website_url: "The website URL of the ad",
    app_url: "The app URL of the ad",
    phone_number: "The phone number of the ad",
    lead_gen_form: "The lead generation form of the ad",
    page_id: "The social media page ID for the ad",
  },
};
